require "common"

if acoustic_scaling == true then
   print('acoustic_scaling = True')
else
   print('acoustic_scaling = False')
end 
print('##Physical parameters##')
print('voidage', voidage)
print('Re =', Re)
print('u_in_p =', u_max_phy)
print('u_mean_p =', u_mean_phy)
print('nu_p =', nu)
print('rho0_p =', rho0_p)
print('length_bnd =', length_bnd)
print('length =', l_ch)
print('height =', h_ch)
print('width =', w_ch)
print('d_f =',d_f)
print('d_h', d_h)
print('dx =',dx)
print('dt =',dt)
print('u_lp =',dx/dt)
print('pr_lp =',math.pow(dx/dt,2.)/3.0*rho0_p)
print('level =', level)
print('')
print('##Lattice parameters##')
print('nLength =', nLength)
print('nLength_bnd =', nLength_bnd)
print('nHeight =', nHeight)
print('nWidth =', nWidth)
print('nDia =', nL)
print('nDia_h =', nL_h)
print('nElems =', nLength*nHeight*nWidth)
print('nSteps =', nSteps)
print('u_in_L =', u_max_L)
print('u_mean_L =', u_mean_L)
print('nu_L =', nu_L)
print('omega =', omega)
