--Prints the parameters from params.lua
require 'params'

print('----------------------')
print('BC Length|', length_bnd)
print('----------------------')
print('level    |', level)
print('----------------------')
print('dx       |', dx)
print('----------------------')
print('dt       |', dt)
print('----------------------')
print('umax     |', umax      )
print('----------------------')
print('uc       |', uc        )
print('----------------------')
print('u_in_L   |', u_in_L)
print('----------------------')
print('Omega    |', omega)
print('----------------------')
print('Re       |', Re)
print('----------------------')
print('Re_L     |', Re_L)
print('----------------------')
print('Pressure |', press_phy)
print('----------------------')
print('mu       |', mu_phy)
print('----------------------')
print('nu       |', nu_phy)
print('----------------------')
